AudereNow/flows

- .gitignore
- src/store/corestore.ts
We can now pull auditor tasks directly from the server, since CSV upload is working.  As we develop Details View a bit more, we'll need to pull more and more data into the actual ClaimTask;  but for now, this replaces our test data with data that came from a CSV.
I haven't updated the Payor view with this data because we'd likely want to enable a real edit flow instead of doing that (i.e. we'll likely want to implement the "click Approve" functionality in order to populate the Payor view with real data).
Here's the data they gave us, pulled from Firestore:
> Pull auditor tasks from server

- functions/src/index.ts
- src/Screens/MainView.tsx
- src/store/corestore.ts
This PR modifies the function that parses CSVs to just create one task per pharmacy, with a sampled set of entries for that pharmacy included in the task, and updates the task list and details view for `ClaimTask` to render appropriately.
The task list entries are super barebones, we'll probably want to add more detail here (and presumably in real CSVs the "pharmacy name" column won't just be a number):
The details might need to be collapsible or something:
> Group claims by pharmacy

- functions/src/index.ts
- src/Components/LabelTextInput.tsx
- src/Components/LabelWrapper.css
- src/Screens/AdminPanel.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.css
- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/africas-talking-key.json
- src/store/corestore.ts
This integrates an Operator tab, and also completes the entire workflow (all the way through to server edits).  Key changes:
* New Role of Operator (the person who calls pharmacies and follows up)
* New OperatorPanel
* Complete flow stored in Firebase.  If an Auditor or Payor declines, the task ends up at the Operator showing their latest notes.  If an Operator completes their work, the task moves to the Payor.  If a Payor marks payment complete, we store the completed task in the payor_complete_tasks folder in Firestore.
* Data model simplification:  since we operate on pharmacies as a basic unit, it seemed simpler just to have Tasks be ClaimTasks.  In other words, a task moves from person to person... but there aren't different types of tasks.  I've also moved Notes into the …
> Implement full task flow

- firebase.json
- firestore.rules
Provide read+write access to your own tasks, and write access to the "next" role's tasks.
Should admins have access to everything, or are they supposed to be strictly for setting other users' roles?
> Add access rules for firestore

- package.json
- src/Components/TaskList.css
- src/Components/TaskList.tsx
- src/store/corestore.ts
- yarn.lock
In a nod to GDocs, this is a proposal for how we deal with multiple active users working in the same role.  TaskList now writes a little piece of data into Firestore whenever a user clicks on a Task.  Every TaskList subscribes to that collection of active task views, and highlights tasks which others are looking at via an on-hover tooltip.  An orange rectangle highlights any task that someone else is looking at simultaneously (within the last 5 mins).
Introduced `react-tooltip` for this instead of writing our own on-hover funniness.  But I'm open to other perspectives on that.
Note that we don't bother deleting stale ActiveTasks from the Firestore collection.  This is assumed to be ok with our very small user base.  At some later point, we can write some sort of cloud function that …
> Show other active users

- functions/src/index.ts
When an admin changes a user's capabilities, we now revoke their auth token so that they get refreshed capabilities the next time they refresh the page.
Tested this with @audererob, and it seems to work.
> Revoke auth tokens when updating user capabilities

- firestore.rules
The actively viewed doc feature that Philip added conflicted with the backend access restrictions I added, so we've been getting this error on every tab:
This PR grants everyone access to the `/actively_viewed_tasks/` collection to fix that error.
> Allow everyone to access actively viewed doc ids

- firestore.rules
- src/Screens/PayorPanel.tsx
- src/store/remoteconfig.ts
Remote Config isn't available on React firebase, and so we implement our own super-basic version of it by storing a "metadata/remoteConfig" object in firestore.  We cache reads of that object, and then provide a `getConfig()` function to load that configuration.
I've also changed things so that the Payor tab by default doesn't allow real issuing of payments.  The button label changes, and the payment-issuing functionality is skipped if real payments aren't enabled.
Here's the config object:
And here's the button label changed based on turning real payments off:
> Introduce remote config and make payments configurable

- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/store/config.ts
- src/store/corestore.ts
I'm trying to do two things with this PR:
* Reduce code duplication across tabs
* Move to a more config-driven UI for flows
To those ends, I created a config file under `src/store` that defines the tabs that show up in our app, and a "TaskPanel" component that is meant to render any workflow step based on that config.
For a normal workflow tab, the configuration lists the collection to load tasks from, and the components to use to render the task list item and the details panel. I also plan to make the accept/decline buttons configurable (they mostly do the same thing: save notes and move the task to a different collection), but for now they're still just hardcoded into the respective "details" components.
For non-workflow tabs like the Admin tab, the config can also just accept a …
> Use a more generic TaskPanel to render Payor and Operator tabs

- src/Screens/PayorPanel.tsx
I added a date column to the payor tab. While doing so, I noticed that the items don't seem to be sorted in any particular order. Should we sort by date?
> FEV-1346: Added date to payor tab

- src/Components/Dropdown.css
- src/Components/LabelWrapper.css
- src/Components/TopBar.css
- src/Components/TopBar.tsx
At present, a user must click on the text inside the filter/nav menus in order to make a selection. This PR makes the entire box around the item clickable.
> FEV-1349: make entire dropdown item box clickable

- firestore.rules
- functions/.gitignore
- functions/package.json
- functions/src/index.ts
- src/Components/NotesAudit.tsx
- src/Components/TaskList.tsx
- src/Components/TopBar.tsx
- src/Screens/AdminPanel.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/store/config.ts
- src/store/corestore.ts
CSV import used to write blobs into an `auditor_todo` collection which were then translated by the client into Task objects.  We now write task objects directly into an `auditor_task` collection.
This PR looks more complicated than it should be because of the difficulty of sharing common types and JS between the main app and cloud functions.  tsconfig and tslint weren't able to reach into ../src/store/corestore.ts without deployment issues, and so I ultimately decided to do the hacky thing by copying the common types during `yarn build` of `functions/`.  If there's a better way to do this (without creating a private module/etc/etc), please LMK.
The changes:
* Extracted common types into sharedtypes.ts.  This required tweaking a bunch of imports.
* Copy that during `yarn build` into …
> Make CSV import write Auditor Tasks

- functions/src/index.ts
- src/sharedtypes.ts
- src/store/remoteconfig.ts
Introduces a remote config `allowDuplicateUploads` which defaults to false.  When CSVs are uploaded, the first row is checked against previous uploads, and the upload is rejected if the same ID was found previously.
Because the cloud function runs async from when the user uploads the file, we track this type of rejected duplication in AdminLogEvent objects, which will in a later PR be shown in the Admin panel.
Here's an example of it rejecting a duplicate CSV:
> Prevent duplication of CSV uploads

- firestore.rules
- functions/src/index.ts
- src/sharedtypes.ts
- src/store/corestore.ts
Currently, metadata about task changes are held in each task.  But tasks travel between collections.  So showing the admin the latest changes is difficult, because you end up going through all collections filtering by TaskChangeMetadata, sorting by the latest change, etc.
We now write the same metadata, enhanced into TaskChangeRecord, into a top-level collection (`task_changes`).  This denormalizes the data so that we can easily search and filter on all changes, and quickly look up tasks via their change records.
This updates the way we write every TaskChangeMetadata so that the denormalization happens.
Here's an example of a change record in the new collection:
> Denormalize task change metadata

- src/Components/LabelTextInput.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
[FEV-1338](https://auderenow.atlassian.net/browse/FEV-1338)
* "defaultValue" on textarea doesn't update on prop change, but "value" does
* Updates local notes state when the task has changed
> Entering a Note on One Task Makes It Appear on All 

- firestore.rules
- functions/src/index.ts
- src/Components/NotesAudit.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/store/config.ts
- src/store/corestore.ts
This implements what we talked about last week, where all tasks now reside in the `tasks` collection, changing state instead of being copied back & forth between different collections.
* Code greatly simplified in corestore, now that it can handle tasks generically.
* Auditor's `entries` editing moved out into the AuditorPanel to maintain corestore genericness
* TaskChangeRecord now not replicated in Task.  This simplifies and normalizes the data model, but required that panels load these change records themselves instead of counting on the replica within each Task.
* CSV upload modified to conform to new data model
* Firebase rules updated to protect reads/writes in the correct way
* Renamed the "operator" state into `FOLLOWUP`,  which I think better reflects what that state actually is. …
> Flatten backend data collections

- functions/src/index.ts
- src/Components/NotesAudit.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.css
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/sharedtypes.ts
- src/store/corestore.ts
This updates how we show notes.
1. We now show all state transitions (instead of just the ones with notes)
2. We label the audit notes area with a header
3. We auto-generate the change description instead of requiring a `desc` in every change
4. We bold the note itself instead of the change.  Looks much better, IMO.
5. We order the changelog by time.  We didn't do that before (!).
> Impvroved notes

- functions/src/index.ts
- src/sharedtypes.ts
This implements full deduplication of CSV uploads on a row-by-row basis by using meta:instanceID from ODK as the unique identifier of records.
* We simplify and flatten the "uploaded records" structure so that one row for each record ever uploaded is stored in the `uploaded_records` collection.
* We scan that collection for newly uploaded meta:instanceIDs, and avoid reinserting IDs we've seen in the past.
* We regenerate a single admin log for each case where a CSV repeats a previously-seen ID.
Note that the "did I previously upload this" search is linear, leading to an O(n^2) implementation of de-duping when it comes to firestore searches.  This is because firestore does not support the concept of querying for records where any of a set of IDs are looked for.  An alternative, faster …
> Deduplicate uploaded records

- src/Components/DateRangePickerOverride.css
- src/Screens/MainView.css
[FEV-54](https://github.com/AudereNow/flows/pull/54)
Overrode some styling with exact pixel values: a bad move, but since the container is "display: relative" and the calendar is "display:absolute" there is nothing we can do in terms of z-index and having the calendar as part of the flow would push all of the search bars, download CSV button, etc down.
> TaskList Expands to Fill Screen When No Results Are Given

- functions/src/index.ts
- src/Components/TopBar.tsx
- src/store/corestore.ts
Now that we have UI to upload files, we make CSV processing synchronous so that we can show the uploading user any errors that happen when processing their upload.
* We no longer use Firebase Storage to store CSVs.  We just process them as strings.
* We've removed the Storage hook `parseCSV`, and are instead now using `uploadCSV`
* We show the user any errors.  Upon success, we tell them how many records were processed.
A future PR will address waiting UI so that the user knows something is happening.  And auto-dismissing the menu.
> Make CSV upload and processing synchronous

- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/TaskPanel.tsx
- src/store/config.ts
This moves @goldjay's search functionality from the Auditor tab to TaskPanel so that it shows up on all the workflow tabs, and uses that to render the Auditor Tab.
I removed the filtering from the Auditor Tab and just split the todo/complete/rejected filter options out into 3 separate tabs.
> Convert Auditor Tab to use TaskPanel

- src/Screens/AuditorPanel.tsx
- src/Screens/TaskPanel.tsx
The approve/decline buttons broke in https://github.com/AudereNow/flows/pull/69, along with showing the default 20% of entries in the details pane.
This also cleans up some of the dead searching/tasklist code that I left behind in the Auditor component.
> Fix a couple auditor panel issues

- src/Screens/TaskPanel.tsx
We previously set an option on `json2csv` that would throw an error if some entries had different fields than others. When Philip added a new field, this broke json generation since not everything matched.
This makes the CSV generation more permissive, including all the fields that appear in any record.
> Fix CSV download

- src/Screens/TaskPanel.tsx
[FEV-1373](https://auderenow.atlassian.net/browse/FEV-1373)
* Changed a weird parenthesis situation and now date is included in the search
Behavior: 
* At least one entry in a pharmacy should fulfill the date range and search / filter parameters
* If one date (start or end) is selected, it should filter the entries accordingly
> Search now takes into account the date range

- src/Screens/TaskPanel.tsx
- src/util/search.ts
[FEV-1375](https://auderenow.atlassian.net/browse/FEV-1375)
* Previously with no filters, all of the entry's keys were being searched for the search term. This lead to some mysterious results with matches in fields that are not displayed.
* Now no filters = all filters
* Changed initial filters to no filters to make it easier to select only one filter
> No Filters: Predictable Search Results

- firestore.rules
- src/Screens/AdminPanel.tsx
- src/store/corestore.ts
This enables us to work on AdminLogEvents in the client a little more:
* We shouldn't include firebase directly, but instead should import frome firebase/app and also specific firebase modules (like firebase/firestore)
* We should put all firestore access in `corestore` so that we can easily refactor storage in an app-independent way.
* This also updates firestore rules so that the admin panel can actually load history
> Firestore fixes for admin log events in client

- src/util/search.ts
[FEV-1377](https://auderenow.atlassian.net/browse/FEV-1377)
Patient info (first, last, age, sex), if undefined, get stringified as "undefined", which counts as a match.
> Catch Undefined Patient Info with Empty String

- src/Screens/MainView.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/store/config.ts
- src/store/remoteconfig.ts
- src/util/configuredComponent.tsx
This adds a `configureComponent()` method that is basically the equivalent of `redux-react`'s `connect()` method, but it ties a component to remote config values rather than redux state. It takes in a component that accepts one or more props that depend on remote config values, a method to map remote config state to those props, and returns a component that only requires the remaining props.
I was able to remove the code in the Payor Details component that explicitly fetched the "realPayments" remote config value, and instead it just accepts it as a prop. The TaskPanel changes were a bit less clean, since the values it needs are based on the config, but it also works there.
I started this PR to address @auderephilip's comment [here](https://github.com/AudereNow/flows/commit/09ba63a792933c3 …
> Pass remote config values as props

- src/App.tsx
- src/Screens/MainView.tsx
- src/Screens/TaskPanel.tsx
- src/store/config.ts
Keep the browser location updated with permalinks whenever you select tabs or tasks so that copy/paste is enabled between users/uses.
- Removed class member that tracked whether to respect `initialSelectedTaskID` in favor of replicating prop into state (which is apparently React's #2 recommendation of how to handle that issue).  This also removed the need to re-key MainView.
- Added `baseUrl` to each tab's config.
- Changed tab name to `Completed` in order to match the case of `Rejected`.
- Enabled /completed and /rejected URLs to be permalinks
> Update URL history with permalinks

- src/Screens/TaskPanel.tsx
> Fix horizontal overflow in tasklist

- src/Screens/MainView.css
- src/Screens/PayorPanel.tsx
- src/store/corestore.ts
Previous tasks are collapsed by default. Expanded, you get a simple table:
> Show previous tasks from the same pharmacy in payor details

- src/Components/SearchableTable.css
- src/Components/SearchableTable.tsx
- src/Screens/AdminPanel.tsx
[FEV-1399](https://auderenow.atlassian.net/browse/FEV-1399)
* On Change History, not all changes have a fromState and toState (rejected, declined, uploads) so I added some logic to get the user doing the action and the action's description. Other than that, the SearchableTable should be the same as ChangeHistory.
> Searchable Admin Logs + Change History

- src/Components/ImageRow.tsx
- src/Components/TextItem.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
This adds a `SearchContext` that is provided by `TaskPanel` and consumed by `TextItem`, so that we don't have to pass `searchTermGlobal` and `filters` down through intermediate components.
> Use React Context to propagate search terms

- src/Components/SearchableTable.tsx
- src/Screens/AdminPanel.tsx
[FEV-1465](https://auderenow.atlassian.net/browse/FEV-1465)
[FEV-1433](https://auderenow.atlassian.net/browse/FEV-1433)
* Allow notes text to wrap around instead of being cut off
NOTE: I could also do this for description, but the description for rejected CSVs is very long so it's not practical
* Merged the two admin tables together
> Merge change history admin logs

- firestore.rules
- src/Components/PharmacyInfo.css
- src/Components/PharmacyInfo.tsx
- src/Screens/AuditorPanel.tsx
- src/sharedtypes.ts
- src/store/corestore.ts
Adds a new collection of pharmacy docs under the `pharmacies` collection in firestore. First use for this is an editable notes field for a pharmacy that persists across tasks.
> FEV-1313 Add pharmacy docs in firestore and editable pharmacy notes

- src/Components/PharmacyInfo.css
- src/Components/PharmacyInfo.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.css
- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/store/config.ts
- src/store/corestore.ts
In the "secondary followup" tab, only show ops team members tasks for pharmacies that they own.
Note: This doesn't apply to primary review. We want to show tasks for unowned pharmacies to every member of the team so that they don't fall through the cracks. Reconciling that with a single list of owners gets tricky, so I'm not going to implement that for now. Afkera said they probably won't need this feature in primary review for a while anyway.
> FEV-1461 Filter tasks by pharmacy owners

- src/Components/ExpandableDiv.css
- src/Components/ExpandableDiv.tsx
- src/Components/PharmacyInfo.tsx
- src/Components/ToolTipIcon.css
- src/Screens/AuditorPanel.tsx
- src/Screens/PayorPanel.tsx
[FEV-1496](https://auderenow.atlassian.net/browse/FEV-1496)
For the future: Tie data fetch to onExpand function like in the payor panel's previous tasks so we don't fetch data no one wants.
> Extra charting within expandable divs + limited tooltip size

- src/Components/PharmacyInfo.tsx
- src/Components/TaskList.tsx
- src/Screens/TaskPanel.tsx
2 fixes:
* Don't save an owner that's just an empty string if you clear the owners textbox
* Load pharmacy info before computing filtered tasks, because otherwise you won't know which pharmacies have other owners
> Fix owners filtering

- src/Components/ClaimNotes.tsx
- src/Components/ListItem.tsx
- src/Components/TaskList.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/OperatorPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/store/config.ts
- src/store/corestore.ts
This is a little weird, but I'm now passing an array of tasks to every task list item and task details component in order to support grouping by pharmacy. On tabs that don't group tasks by pharmacy (completed/rejected/secondary followup), the array is always of length one. For the auditor and payor tabs, the array contains all of the tasks for a given pharmacy currently in that task state.
> Group tasks by pharmacy in auditor/payor tabs

- src/Components/ClaimNotes.tsx
- src/Screens/AuditorPanel.tsx
- src/store/corestore.ts
`task.foundCount` is sometimes `undefined`, but firestore doesn't allow `undefined` values in documents. Clean them out before saving.
> Remove foundCount before saving task

- package.json
- src/Components/NotesAudit.css
- src/Components/NotesAudit.tsx
- src/Components/SearchableTable.tsx
- src/Screens/AdminPanel.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/store/corestore.ts
- yarn.lock
The translated the audit log messages from things like `Ram Kandasamy moved from CSV to AUDIT 21 days ago` to `Ram Kandasamy uploaded for primary review 21 days ago`, and adds more details when it's a payment, e.g.:
or
> Better payment details and audit log messages

- src/Components/NotesAudit.tsx
> Remove orphaned tooltip

- package.json
- src/App.tsx
- src/Components/Button.css
- src/Components/LabelWrapper.css
- src/Components/LabelWrapper.tsx
- src/Components/TopBar.css
- src/Screens/AdminPanel.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainChrome.css
- src/Screens/MainChrome.tsx
- src/Screens/MainView.css
- src/Screens/TaskPanel.tsx
- yarn.lock
Fixes https://auderenow.atlassian.net/browse/AUD-1829
Upgraded react-scripts to get optional chaining support in typescript, some CSS fixes to avoid having 3 nested divs each with their own vertical scrollbars, and fixing a bug with routing to the admin tab.
Most of then lines changed are just `yarn.lock` changes from the react-scripts upgrade.
* No
> AUD-1829 Bump react-scripts version, fix some scrolling and react-router issues

- package.json
- src/Components/CheckBox.css
- src/Components/CheckBox.tsx
- src/Screens/AuditorPanel.css
- src/Screens/AuditorPanel.tsx
- src/Screens/TaskPanel.tsx
Fixes: https://auderenow.atlassian.net/browse/AUD-1837
Allow reviewers to select approve/hold/reject for individual claims, or flag them for patient review (i.e. tell the next reviewer for this claim to call that patient and verify that the transaction really happened). For the first two review stages, reviewers will have to approve at least 20% of the claims before bulk-approving the rest of the claims for the facility using the big "approve" button at the bottom of the page. Individual claims that were rejected get sent to rejection review instead, and held claims stay in their current state.
They wanted to make sure people didn't accidentally bulk-decline claims, so we show this confirmation dialog:
The individual claim selections are saved to local storage in case you refresh the page …
> AUD-1837 Better triage options for individual claims

- package.json
- src/Components/ListItem.tsx
- src/Components/TaskList.tsx
- src/Screens/AuditorPanel.css
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/PayorPanel.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/transport/baseDatastore.ts
- src/transport/maisha.ts
- src/transport/maishaDatastore.ts
- yarn.lock
Rather than fetching every claim for every pharmacy up front, only load the claims for the pharmacy you've selected.
For pharmacies with >25 claims, add pagination rather than rendering all of them at once. They load in the background so you can start reviewing claims before they all load:
* No
> AUD-1736 Load claims only for selected pharmacy

- src/Components/ToolTipIcon.css
- src/Screens/AuditorPanel.tsx
- src/Screens/TaskPanel.tsx
Add a border, and use a slightly more compelling example query in the tooltip.
* No
> AUD-1736 Update search tooltip

- src/Screens/AuditorPanel.tsx
Previously we marked any claim that was visible to the user as manually reviewed when the batch got reviewed. Now that we have explicit radio buttons for each claim, we use those selections to indicate if a claim was manually reviewed or not instead. Removing this old logic.
* No
> AUD-1736 Remove old reviewed flag handling

- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.css
- src/transport/baseDatastore.ts
Split out the patient review flag (and any other manually created flags) from the regular flags in order to highlight them. Sort claims by descending number of flags, with manual ones taking precedence.
* No
> Highlight manually created flags

- src/Components/ClaimNotes.css
- src/Components/ClaimNotes.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/OperatorPanel.tsx
- src/sharedtypes.ts
- src/transport/firestore.ts
- src/transport/maisha.ts
- src/transport/maishaDatastore.ts
Notes is now a list, not a single string, so render it appropriately. Notes can be multiline, so I added a border between notes.
* No
> Render claim notes

- src/Components/LabelWrapper.tsx
- src/Components/ListItem.tsx
- src/Components/TaskList.css
- src/Components/TaskList.tsx
- src/Screens/AuditorPanel.tsx
- src/Screens/MainView.tsx
- src/Screens/TaskPanel.tsx
- src/sharedtypes.ts
- src/store/config.ts
- src/transport/baseDatastore.ts
- src/transport/maisha.ts
- src/transport/maishaDatastore.ts
- src/util/tasks.ts
Instead of just grouping by pharmacy, group by pharmacy and the date of the last action.
I had to change the path handling logic a bit in `TaskPanel` to deal with multiple groups using the same pharmacy ID, and also I have to load all the tasks in complete/rejected, because that's where the last action timestamp is.
> Group completed and rejected claims by last action

- src/Screens/TaskPanel.tsx
Something about the way this code was happening before was stopping
approvals from including patient review flags, so I've made it slightly
simpler to reason about by removing the ternary.
> Actually flag tasks for patient review
