AudereNow/flows

src/Components/Button.css, src/Components/Button.tsx, src/Components/DataTable.css, src/Components/DataTable.tsx, src/Components/ImageRow.css, src/Components/ImageRow.tsx, src/Components/LabelTextInput.css, src/Components/LabelTextInput.tsx, src/Components/LabelWrapper.css, src/Components/LabelWrapper.tsx, src/Components/TaskList.tsx, src/Components/TextItem.css, src/Components/TextItem.tsx, src/Screens/MainView.css, src/Screens/MainView.tsx
* Basic UI for details pages
* Image Zoom
Next Steps:
* Re-do details UI on a by-pharmacy basis once the data shape is changed
* Search claims
=> Details Views

src/Screens/MainView.tsx, src/store/corestore.ts
* Added age and sex to ClaimTask (They were in the Sketch spec, but not on ClaimTask)
* Fixed patientID key
=> More ClaimTask Properties

functions/src/index.ts
It feels weird to return from the function before we've finished processing the CSV.
=> Wait for data to get saved to firestore before returning from parseCSV

src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/MainView.tsx, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/util/debounce.ts, src/util/search.ts
* Search by values i.e. patient name, date or item
* Search by specific key using a ":" ex: "item:e" searches for all detail items with an item value that contains "e"
* Debounced input for less jarring UX
=> Details Search Auditor View

functions/.gitignore, functions/package.json, functions/src/index.ts, functions/tsconfig.json, functions/yarn.lock, src/Components/Button.css, src/Components/Button.tsx, src/Screens/MainView.css, src/Screens/PayorPanel.tsx, src/africas-talking-key.json, src/store/corestore.ts
The following changes are included:
* A cloud function that calls the REST APIs for payments
* A JSON file with the actual API key which needs to be installed on every engineer's machine (stored in LastPass)
* An enhanced Payor tab with the new functionality
* Added ability to disable a Button
=> Implements payments via Africa's Talking

src/Components/Dropdown.css, src/Components/Dropdown.tsx, src/Components/HamburgerIcon.css, src/Components/HamburgerIcon.tsx, src/Components/TopBar.css, src/Components/TopBar.tsx, src/Screens/MainView.css
* Configurable Dropdown Menu
* Added CSS to TaskList to change color on hover and have the pointer cursor
* Logout Functionality
Q: HamburgerIcon is in HTML/CSS. Should it be in /assets?
=> Dropdown Menu + TaskList Hover Behavior

src/Components/NotesAudit.css, src/Components/NotesAudit.tsx, src/Components/TopBar.css, src/Components/TopBar.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/store/corestore.ts
=> Notes Audit Trail for Operator and Payor

src/Components/Dropdown.css, src/Components/ImageRow.tsx, src/Components/LabelWrapper.css, src/Components/LabelWrapperWithSearch.css, src/Components/LabelWrapperWithSearch.tsx, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx
=> Dropdown Menu Styling + Unique Key Warnings

src/Components/Dropdown.tsx, src/Components/TopBar.tsx
CSV uploads weren't working because the menu disappeared lost focus while you were selecting the file to upload. Pin it in place while you're selecting the file.
=> Fix CSV uploads

src/Screens/OperatorPanel.tsx, src/store/corestore.ts
Also renamed the methods for code hygiene's sake.
=> FEV-1339 change "Mark Completed" to "Approve for Payment"

src/Screens/AuditorPanel.tsx
[FEV-1340](https://auderenow.atlassian.net/browse/FEV-1340)
* Notes input on Auditor tab only shows when looking at "to-do" items.
=> Completed and Rejected Claims Show Notes Input

src/store/corestore.ts
Addressing https://github.com/AudereNow/flows/pull/38#discussion_r336159898
=> Remove unused method

src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx
* Wrapper around operator + payor panel tasklists
* flexbox based styling for tasklist container and details container for no stutter on content load
=> Operator and Payor Panels Have no Task List Label

src/Components/LabelTextInput.tsx, src/Screens/AuditorPanel.tsx, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx
* Only changed the name of defaultValue to value
=> Requested Change for FEV-1338

src/Components/LabelWrapper.css
[FEV-1347](https://auderenow.atlassian.net/browse/FEV-1347)
=> TaskList and Details Extend Off Screen

firestore.rules
Now that #56 has landed, we can remove old collections and update the rules.  I've verified that everything works as expected off master.
=> Clean up rules for simplified collections

package.json, src/Components/TopBar.tsx, src/Screens/MainChrome.tsx, src/Screens/MainView.css, yarn.lock
I originally tried to limit the change only to TopBar, using `position:fixed` in hopes of overlaying the whole screen, but the spinner got limited to just the menu itself.  Does anyone know whether, perhaps, something like `float` would make it possible to make the spinner's div paint over the whole screen?  That'd be ideal from an encapsulation perspective.
=> Show full screen spinner when processing CSV

src/Components/HighlightText.css, src/Components/HighlightText.tsx, src/Components/ImageRow.css, src/Components/ImageRow.tsx, src/Components/LabelWrapper.css, src/Components/TextItem.css, src/Components/TextItem.tsx, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/MainView.tsx, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx, src/util/search.ts
[FEV-1345](https://auderenow.atlassian.net/browse/FEV-1345)
Behavior:
* Case-sensitive search
* Filters to search based on specific fields
=> Highlight relevant text and show all entries on search term found

src/Components/ListItem.tsx, src/Screens/MainView.css, src/Screens/TaskPanel.tsx
* Ticking a checkbox triggers search [FEV-1370](https://auderenow.atlassian.net/browse/FEV-1370)
* Can check a box by clicking on the label [FEV-1371](https://auderenow.atlassian.net/browse/FEV-1371) 
* All filters initially enabled [FEV-1372](https://auderenow.atlassian.net/browse/FEV-1372)
=> Checkbox Improvements

src/Components/TaskList.css, src/Components/TaskList.tsx, src/Screens/OperatorPanel.tsx, src/Screens/TaskPanel.tsx
[FEV-1374](https://auderenow.atlassian.net/browse/FEV-1374)
TIL about position: sticky
=> Search Bar Appears at Top of TaskList when scrolling

src/Screens/AdminPanel.tsx, src/store/corestore.ts
... and also clear the UI when done setting roles.
=> Give admin feedback about SetRole success/failure

src/Components/ChangeHistory.tsx, src/Screens/AdminPanel.tsx, src/store/corestore.ts
Yes, it's nasty, but we'll soon design this to actually be usable (e.g. look good, present notes only when relevant, permalink to tasks for drill-down, show dates readably, be sortable / searchable, pagination).  For now, this gets the data in there and lets us enhance it in parallel.
=> Show admin full history

src/Components/HighlightText.tsx, src/Screens/TaskPanel.tsx, src/util/search.ts
[FEV-1369](https://auderenow.atlassian.net/browse/FEV-1369)
=> Case-Insensitive Search

package.json, src/Components/ChangeHistory.tsx, yarn.lock
We integrate `react-table`, which supports column widths, paging, sorting, and a bunch of other things automatically.
=> Much better TaskChangeRecord rendering

functions/src/index.ts, src/store/corestore.ts
Two things:
1. When the CSV has issues (e.g. firestore throws), turn the error into something communicated back to the user
2. Catch a bunch of client-side errors that can happen when the server throws.
Addresses user-reported error where CSV processing is silently failing on the server.
=> Better error propagation to user

src/Components/ChangeHistory.css, src/Components/ChangeHistory.tsx, src/Components/CheckBox.css, src/Components/CheckBox.tsx, src/Components/ImageRow.tsx, src/Components/TextItem.tsx, src/Screens/AdminPanel.tsx, src/Screens/MainView.css, src/Screens/TaskPanel.tsx, src/util/search.ts
Search changes as you would tasks.
* No filters = all filters
* Special case for timestamp: Search as displayed i.e. "2 days..."
=> Search Changes

src/Components/LabelWrapper.css, src/Components/LabelWrapper.tsx
=> Restore Number of Entries Text on LabelWrapper

src/Screens/MainView.css, src/Screens/TaskPanel.tsx
[FEV-1412](https://auderenow.atlassian.net/browse/FEV-1412)
=> Recalculate Changes on Search

src/Components/SearchableTable.tsx, src/Screens/AdminPanel.tsx
* Download in Correct Order
* Date timestamp with relative time tooltip
=> CSV Download Fix

src/Screens/AuditorPanel.tsx, src/Screens/OperatorPanel.tsx, src/util/search.ts
[FEV-1466](https://auderenow.atlassian.net/browse/FEV-1466)
=> Added phone to patient and made searchable with patient filter

src/Screens/MainView.tsx, src/Screens/TaskPanel.tsx
Looks like some of the permalink code was accidentally reverted in https://github.com/AudereNow/flows/commit/34de63d82d1c43a2326bbe0ff2880fd4ca033ede, this PR unreverts those changes.
=> FEV-1432 Re-enable permalinks to tasks

src/Components/CheckBox.css, src/Components/CheckBox.tsx, src/Components/ImageRow.tsx, src/Components/LabelWrapper.css, src/Components/PharmacyInfo.css, src/Components/PharmacyInfo.tsx, src/Components/SearchableTable.tsx, src/Components/TextItem.css, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.tsx, src/Screens/OperatorPanel.tsx, src/Screens/TaskPanel.tsx, src/store/config.ts
[FEV-1480](https://auderenow.atlassian.net/browse/FEV-1480)
* Also fixed admin / change history csv download
* Also removed the helper on PharmacyInfo in favor of clearing state with name prop change
=> Global collapse of images

src/Components/PharmacyInfo.css, src/Components/PharmacyInfo.tsx, src/Components/ToolTipIcon.css, src/Components/ToolTipIcon.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx, src/store/config.ts, src/store/corestore.ts
[FEV-1460](https://auderenow.atlassian.net/browse/FEV-1460)
=> Display previous claims + flag increases > 50%

firestore.rules, functions/src/index.ts, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/sharedtypes.ts, src/store/corestore.ts
=> FEV-1459 Show patient histories in auditor tab

src/Screens/AdminPanel.tsx, src/store/corestore.ts
Test payments are limited to 500Ksh, but otherwise this just lets you send an arbitrary amount of money to an arbitrary phone number.
=> Add a payment test form under the advanced tab

src/Screens/AuditorPanel.tsx, src/store/corestore.ts
=> Factor out function to get all docs

firestore.rules, src/Components/CheckBox.tsx, src/Screens/AdminPanel.tsx, src/store/remoteconfig.ts
=> Add toggles for remote config options to Admin Tab

src/Screens/AuditorPanel.tsx, src/Screens/MainView.css
* Missed coloring of a couple pieces of text
=> Unstyled Text

package.json, src/Screens/AdminPanel.tsx, src/Screens/MainView.css, src/Screens/OperatorPanel.tsx, src/sharedtypes.ts, src/store/corestore.ts, src/store/remoteconfig.ts, yarn.lock
Show some instructions for ops team members:
Admins can edit the instructions:
=> Editable instructions for ops team

src/Components/CheckBox.css, src/Components/ClaimNotes.css, src/Components/ClaimNotes.tsx, src/Components/PharmacyInfo.tsx, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx, src/store/corestore.ts
* Search was broken
* Ability to reject individual claims not included
* Download CSV included undefined fields + extra fields
=> Misc Fixes

src/Components/Button.css, src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/TaskPanel.tsx
[FEV-1470
](https://auderenow.atlassian.net/browse/FEV-1470)
=> Number of claims that match pharmacy-level search term

functions/src/index.ts, src/Components/TopBar.tsx
Looks like this was already included in the uploadCSV cloud function, but it wasn't deployed. 
While testing I found that the upload CSV button wasn't working so I fixed it.
=> Pharmacy Phone

src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/OperatorPanel.tsx, src/Screens/TaskPanel.tsx, src/sharedtypes.ts, src/store/config.ts, src/store/corestore.ts
[FEV-1479](https://auderenow.atlassian.net/browse/FEV-1479)
* Button on Auditor panel to save current notes
=> Save Notes Without Changing Task State

src/Components/SearchableTable.tsx, src/Screens/AdminPanel.tsx, src/Screens/MainView.tsx
[FEV-1432](https://auderenow.atlassian.net/browse/FEV-1432)
* Click on an id in the change logs and it will take you to that task in the application
=> Change History id links to task in application

src/Screens/MainView.tsx
Needed a way to differentiate the props from a link navigation vs. tab navigation.
=> Tab navigation fix

firestore-debug.log, src/Components/Notes.css, src/Components/Notes.tsx, src/Components/PharmacyInfo.css, src/Components/PharmacyInfo.tsx, src/Components/TopBar.tsx, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/store/config.ts, src/store/corestore.ts
* Changed search keys on several items so the patient id shows up in patient searches and the pharmacy phone number shows up for pharmacy
* History Table changed to cursor:pointer to make it more obvious that it's a link.
=> Misc fixes: styling and individual claim notes

src/Screens/PayorPanel.tsx
[FEV-1435](https://auderenow.atlassian.net/browse/FEV-1435)
=> Added rejected status to payor panel

src/Screens/OperatorPanel.tsx
[FEV-1404](https://auderenow.atlassian.net/browse/FEV-1404)
=> Claim notes for the operator panel

src/Components/CheckBox.css, src/Components/CheckBox.tsx, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx
[FEV-1545](https://auderenow.atlassian.net/browse/FEV-1545)
=> Checkbox label click doesn't toggle checkbox

src/Components/SearchableTable.tsx
[FEV-1448](https://auderenow.atlassian.net/browse/FEV-1448)
=> export time changed to localeDateString

src/Screens/MainView.tsx, src/Screens/TaskPanel.tsx
Tab indices were being looked up with the assumption that every user sees every tab. We need to filter by role before doing the lookup.
=> FEV-1543 Fix tab index lookup

src/App.tsx, src/Screens/AdminPanel.tsx
=> FEV-1546 Add permalinks to admin sub-tabs

.prettierrc.json, functions/src/index.ts, src/App.tsx, src/Components/CannedNotesEditor.tsx, src/Components/ClaimNotes.tsx, src/Components/LabelWrapper.tsx, src/Components/NotesAudit.tsx, src/Components/PharmacyInfo.tsx, src/Components/SearchableTable.tsx, src/Components/TaskList.tsx, src/Components/TextItem.tsx, src/Components/TopBar.tsx, src/Components/ZoomableImage.tsx, src/Screens/AdminPanel.tsx, src/Screens/AuditorPanel.tsx, src/Screens/MainView.tsx, src/Screens/OperatorPanel.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx, src/sharedtypes.ts, src/store/config.ts, src/store/corestore.ts, src/store/remoteconfig.ts
Added a `.prettierrc.json` file and ran `prettier` on everything.
=> Rerun prettier on flows repo

PULL_REQUEST_TEMPLATE.md
Fixes: https://auderenow.atlassian.net/browse/AUD-1773 PR template for `flows` repo
Copied straight from https://github.com/AudereNow/openrdt-internal/blob/master/PULL_REQUEST_TEMPLATE.md. 
N/A
**Test plan (required)**
N/A
**Automation**
* This submission does not require new automated tests 
* Yes
=> AUD-1773 PR template for flows

src/Components/TopBar.tsx, src/Screens/LoginScreen.tsx
Fixes: https://auderenow.atlassian.net/browse/AUD-1738
This adds an extremely barebones login form to hit Maisha's login endpoint.
* No
=> AUD-1738 Alternate login screen for use with Maisha API

src/Screens/AuditorPanel.tsx, src/Screens/MainView.css, src/Screens/MainView.tsx, src/Screens/TaskPanel.tsx
Fixes: https://auderenow.atlassian.net/browse/AUD-1836
Fetch flags from Maisha and display them at the top of each claim.
* No
=> AUD-1836 Maisha claim flags

src/store/config.ts
Fixes: https://auderenow.atlassian.net/browse/AUD-1838
Update config to show the set of tabs (i.e. workflow steps) Maisha requested:
* No
=> AUD-1838 Update config with additional tabs

src/Screens/AuditorPanel.tsx, src/Screens/OperatorPanel.tsx, src/Screens/TaskPanel.tsx, src/sharedtypes.ts
Fixes: https://auderenow.atlassian.net/browse/AUD1736
=> AUD-1736 Fix broken build

src/Screens/AuditorPanel.tsx, src/Screens/PayorPanel.tsx, src/Screens/TaskPanel.tsx
The Maisha API doesn't support everything that was in the firebase version, so these buttons don't work. Hide them.
* No
=> AUD-1736 Hide some buttons that don't work

src/Components/SearchableTable.tsx, src/util/search.ts
Make search actually case-insensitive (it previously never matched a search term if it contained capital letters), and split terms using spaces instead of commas.
* No
=> AUD-1736 Fix search behavior

src/Screens/AdminPanel.tsx
Adds a button to reset all claims to their initial state. The admin tab now only shows up in development mode, this is not for production use.
* No
=> AUD-1736 Add button to reset claims for local development

package.json, src/store/config.ts
=> Use production endpoint for prod

src/Components/Notes.tsx
=> AUD-1736 Hide previous actions and canned responses selector if none available

src/transport/maisha.ts, src/transport/maishaDatastore.ts
Fixes: https://auderenow.atlassian.net/browse/AUD-xxxx
* No
=> AUD-1736 Include loyalty_product_id in item labels

src/Screens/PayorPanel.tsx
M-Pesa is the mobile payments provider that Maisha uses to pay pharmacies. To track payments, they want to record the transaction confirmation numbers when they pay out claims:
Also update the way we render items and add reimbursement amounts to the table on this page:
* No
=> AUD-1736 Billing Panel updates

src/Components/ClaimNotes.tsx, src/Components/Notes.tsx, src/Screens/AuditorPanel.tsx, src/Screens/OperatorPanel.tsx, src/Screens/TaskPanel.tsx, src/store/config.ts
Hardcode in Mac's requested canned responses for first review:
And patient review:
* No
=> Add hardcoded canned responses

src/Components/LabelWrapper.css, src/Components/LabelWrapper.tsx, src/Screens/AuditorPanel.tsx
=> Collapse patients after selecting an action

README.md, src/App.tsx, src/transport/datastore.ts, src/transport/firestore.ts
=> AUD-1736 Add local setup instructions to README

src/Components/ClaimNotes.css, src/Components/ClaimNotes.tsx, src/transport/baseDatastore.ts, src/transport/maishaDatastore.ts
Add a history link for claims.
=> Add a history link

src/Components/LabelWrapper.tsx, src/Components/ListItem.tsx, src/Screens/TaskPanel.tsx, src/store/config.ts, src/transport/maisha.ts
Use "Billed/Rejected On", not "Last Modified".
=> Change last modified label

package.json, tsconfig.json, yarn.lock
This eliminates a bunch of warnings in the build process.
=> Upgrade react-scripts to 4.0.0
